.DEFAULT_GOAL := install

latest_version := $(shell curl --silent "https://api.github.com/repos/k0sproject/k0s/releases/latest" | jq --raw-output '.assets[] | select(.name | test("k0s-.*-amd64$$")).browser_download_url')

.PHONY: clean
clean:
	sudo rm --force /usr/local/bin/k0s

.PHONY: download
download: clean
	sudo wget --no-clobber --output-document /usr/local/bin/k0s "$(latest_version)"

.PHONY: install
install: download
	sudo chmod +x /usr/local/bin/k0s
