.DEFAULT_GOAL := configure

.PHONY: install
install:
	sudo apt install --yes /tmp/barracudavpn*amd64.deb
	sudo mkdir --parents "/etc/barracudavpn/ca"

.PHONY: configure
configure: install
	test -d "$(HOME)/.barracudavpn/"
	sudo cp "$(HOME)/.barracudavpn/barracudavpn.conf" "/etc/barracudavpn/"
	sudo chown root:root "/etc/barracudavpn/barracudavpn.conf"
	sudo chmod 600 "/etc/barracudavpn/barracudavpn.conf"
