tz = Europe/Berlin

.PHONY: timezone
timezone: localtime
	echo "$(tz)" > /etc/timezone

.PHONY: localtime
localtime: install
	ln --symbolic --force "/usr/share/zoneinfo/$(tz)" /etc/localtime

.PHONY: install
install:
	apt-get install --yes tzdata
