.DEFAULT_GOAL := clone

.PHONY: clean
clean:
	rm --recursive --force "$(HOME)/.vim/"

.PHONY: clone
clone: clean
	git clone https://github.com/tpope/vim-pathogen.git "$(HOME)/.vim"
	git clone https://github.com/scrooloose/nerdtree.git "$(HOME)/.vim/bundle/nerdtree"
	git clone https://github.com/vim-airline/vim-airline.git "$(HOME)/.vim/bundle/vim-airline"
	git clone https://github.com/vim-airline/vim-airline-themes.git "$(HOME)/.vim/bundle/vim-airline-themes"
	git clone https://github.com/altercation/vim-colors-solarized.git "$(HOME)/.vim/bundle/vim-colors-solarized"
	git clone https://github.com/drmikehenry/vim-fixkey.git "$(HOME)/.vim/bundle/vim-fixkey"
