.DEFAULT_GOAL := connections

.PHONY: install
install:
	sudo apt install --yes network-manager openvpn network-manager-openvpn network-manager-openvpn-gnome vpnc network-manager-vpnc network-manager-vpnc-gnome resolvconf

.PHONY: connections
connections: install
	sudo cp --force $(HOME)/.network/* /etc/NetworkManager/system-connections/
