.DEFAULT_GOAL := symlink

.PHONY: directories
directories:
	mkdir --parents "$(HOME)/Documents/workspace/private" "$(HOME)/Documents/workspace/work"

.PHONY: symlink
symlink: directories
	ln --symbolic --force "$(HOME)/Documents/workspace" "$(HOME)/workspace"
