.DEFAULT_GOAL := clone

.PHONY: clean
clean:
	sudo rm --recursive --force /usr/local/bin/adr-tools/

.PHONY: clone
clone: clean
	sudo git clone https://github.com/npryce/adr-tools.git /usr/local/bin/adr-tools
