.DEFAULT_GOAL := install

.PHONY: repository
repository:
	sudo add-apt-repository --yes ppa:obsproject/obs-studio

.PHONY: update
update: repository
	sudo apt-get update

.PHONY: install
install: update
	sudo apt-get install --yes obs-studio
