dotfiles = $(shell find "$(HOME)/dotfiles" -maxdepth 1 -name ".*" -not -name .git -not -name .github -printf '%f\n')

.PHONY: symlink
symlink:
	test -d "$(HOME)/dotfiles"
	for file in $(dotfiles); do \
		if [ ! -e "$(HOME)/$$file" ]; then \
			ln --symbolic --force "$(HOME)/dotfiles/$$file" "$(HOME)/$$file"; \
		fi; \
	done
