.DEFAULT_GOAL := install

.PHONY: key
key:
	curl --silent --show-error --location https://rvm.io/mpapis.asc | gpg --import -

.PHONY: install
install: key
	curl --silent --show-error --location https://get.rvm.io | bash -s stable
