.DEFAULT_GOAL := install

latest_version := $(shell curl --silent "https://api.github.com/repos/balena-io/etcher/releases/latest" | jq --raw-output '.assets[] | select(.name | test(".*.amd64.deb")).browser_download_url')

.PHONY: clean
clean:
	rm --force /tmp/balena-etcher*.deb

.PHONY: download
download: clean
	wget --no-clobber --directory-prefix /tmp --content-disposition "$(latest_version)"

.PHONY: install
install: download
	sudo apt install --yes /tmp/balena-etcher*.deb
