LSB_RELEASE := $(shell lsb_release -r -s)
ifneq ($(LSB_RELEASE),22.04)
	PIP_OPTS = --break-system-packages
endif

.PHONY: update
update:
	sudo apt-get update

.PHONY: install
install: update
	pip3 install --disable-pip-version-check --upgrade $(PIP_OPTS) ansible molecule molecule-plugins[docker] ansible-lint pytest-testinfra ansible-dev-tools flake8 yamllint
	sudo apt-get install --yes sshpass python3-jmespath python3-passlib python3-bcrypt
