.DEFAULT_GOAL := repository

.PHONY: clean
clean:
	rm --force /tmp/teamviewer*.deb

.PHONY: download
download: clean
	wget --no-clobber --directory-prefix /tmp --content-disposition "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"

.PHONY: install
install: download
	sudo apt install --yes /tmp/teamviewer*.deb

.PHONY: repository
repository: install
	sudo teamviewer repo default
