.DEFAULT_GOAL := automatic

.PHONY: install
install:
	sudo apt-get install --yes needrestart

.PHONY: automatic
automatic: install
	sudo sh -c 'echo "\$$nrconf{restart} = \"a\";" > /etc/needrestart/conf.d/auto_restart.conf'
	sudo sh -c 'echo "\$$nrconf{kernelhints} = -1;" > /etc/needrestart/conf.d/hide_kernelhints.conf'
