.DEFAULT_GOAL := install

.PHONY: repository
repository:
	sudo add-apt-repository --yes ppa:ansible/ansible

.PHONY: update
update: repository
	sudo apt update

.PHONY: install
install: update
	sudo apt install --yes ansible python3-jmespath python3-passlib python3-bcrypt
