.PHONY: install
install: update
	sudo apt-get install --yes papirus-icon-theme

.PHONY: update
update: repository
	sudo apt-get update

.PHONY: repository
repository:
	sudo add-apt-repository --yes ppa:papirus/papirus
