.PHONY: default
default:
	$(MAKE) --file Makefile.workspace
	$(MAKE) --file Makefile.dotfiles
	$(MAKE) --file Makefile.secrets
	$(MAKE) --file Makefile.local
	$(MAKE) --file Makefile.apt
	$(MAKE) --file Makefile.network
	$(MAKE) --file Makefile.timezone
	$(MAKE) --file Makefile.needrestart
	$(MAKE) --file Makefile.pkg-install
	$(MAKE) --file Makefile.pkg-erase
	$(MAKE) --file Makefile.ansible
	$(MAKE) --file Makefile.chrome
	$(MAKE) --file Makefile.cookiecutter
	$(MAKE) --file Makefile.dircolors
	$(MAKE) --file Makefile.docker
	$(MAKE) --file Makefile.docker-compose
	$(MAKE) --file Makefile.hadolint
	$(MAKE) --file Makefile.azure-cli
	$(MAKE) --file Makefile.hcloudcli
	$(MAKE) --file Makefile.google-cloud-sdk
	$(MAKE) --file Makefile.edge
	$(MAKE) --file Makefile.editorconfig-checker
	$(MAKE) --file Makefile.etcher
	$(MAKE) --file Makefile.git
	$(MAKE) --file Makefile.prettier
	$(MAKE) --file Makefile.pre_commit
	$(MAKE) --file Makefile.gitleaks
	$(MAKE) --file Makefile.golang
	$(MAKE) --file Makefile.gnometerminal
	$(MAKE) --file Makefile.hamster
	$(MAKE) --file Makefile.helm
	$(MAKE) --file Makefile.hugo
	$(MAKE) --file Makefile.keepassxc
	$(MAKE) --file Makefile.kubectl
	$(MAKE) --file Makefile.minikube
	$(MAKE) --file Makefile.nodejs
	$(MAKE) --file Makefile.lens
	$(MAKE) --file Makefile.logcli
	$(MAKE) --file Makefile.nerdfonts
	$(MAKE) --file Makefile.poetry
	$(MAKE) --file Makefile.ohmyzsh
	$(MAKE) --file Makefile.papirus
	$(MAKE) --file Makefile.shellcheck
	$(MAKE) --file Makefile.staticcheck
	$(MAKE) --file Makefile.sweethome3d
	$(MAKE) --file Makefile.teamviewer
	$(MAKE) --file Makefile.terraform
	$(MAKE) --file Makefile.truststore
	$(MAKE) --file Makefile.tmux-plugins
	$(MAKE) --file Makefile.virtualbox
	$(MAKE) --file Makefile.vagrant
	$(MAKE) --file Makefile.vagrant-plugins
	$(MAKE) --file Makefile.vim-plugins
	$(MAKE) --file Makefile.vscode
	$(MAKE) --file Makefile.yq
	$(MAKE) --file Makefile.yt-dlp
	$(MAKE) --file Makefile.gsettings

.PHONY: optional
optional:
	$(MAKE) --file Makefile.barracudavpn
