.DEFAULT_GOAL := all

.PHONY: install
install:
	sudo apt-get install --yes apt-transport-https

.PHONY: timeout
timeout:
	sudo sh -c 'echo "Acquire::http::Timeout \"5\";\nAcquire::https::Timeout \"5\";\nAcquire::ftp::Timeout \"5\";" > /etc/apt/apt.conf.d/99timeout'

.PHONY: all
all: install timeout
