.DEFAULT_GOAL := install

latest_version := $(shell curl --silent "https://api.github.com/repos/hadolint/hadolint/releases/latest" | jq --raw-output '.assets[] | select(.name | test("hadolint-Linux-x86_64$$")).browser_download_url')

.PHONY: clean
clean:
	sudo rm --force /usr/local/bin/hadolint

.PHONY: download
download: clean
	sudo wget --quiet --no-clobber --output-document /usr/local/bin/hadolint "$(latest_version)"

.PHONY: install
install: download
	sudo chmod +x /usr/local/bin/hadolint
