dotfiles = $(shell find "$(HOME)/secrets" -maxdepth 1 -name ".*" -printf '%f\n')

.PHONY: symlink
symlink:
	for file in $(dotfiles); do \
		if [ ! -e "$(HOME)/$$file" ]; then \
			ln --symbolic --force "$(HOME)/secrets/$$file" "$(HOME)/$$file"; \
		fi; \
	done
