.PHONY: vboxconfig
vboxconfig: install
	sudo /sbin/vboxconfig

.PHONY: install
install: update
	sudo apt-get install --yes virtualbox-5.2 dkms

.PHONY: update
update: repository
	sudo apt-get update

.PHONY: repository
repository:
	sudo sh -c 'echo "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bionic contrib" > /etc/apt/sources.list.d/oracle_virtualbox.list'
