.DEFAULT_GOAL := install

latest_version := $(shell curl --silent "https://api.github.com/repos/jsonnet-bundler/jsonnet-bundler/releases/latest" | jq --raw-output '.assets[] | select(.name | test(".*-linux-amd64$$")).browser_download_url')

.PHONY: clean
clean:
	sudo rm --force /usr/local/bin/jb

.PHONY: download
download: clean
	sudo wget --no-clobber --output-document /usr/local/bin/jb "$(latest_version)"

.PHONY: install
install: download
	sudo chmod +x /usr/local/bin/jb
