.DEFAULT_GOAL := apply

.PHONY: install
install:
	sudo apt-get install --yes network-manager openvpn network-manager-openvpn network-manager-openvpn-gnome vpnc network-manager-vpnc network-manager-vpnc-gnome resolvconf

.PHONY: connections
connections: install
	sudo cp --preserve=mode,ownership --force $(HOME)/.network/* /etc/netplan/

.PHONY: apply
apply: connections
	sudo netplan apply
