.DEFAULT_GOAL := install

.PHONY: repository
repository:
	sudo sh -c 'echo "deb https://deb.etcher.io stable etcher" > /etc/apt/sources.list.d/etcher.list'

.PHONY: key
key: repository
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 379CE192D401AB61

.PHONY: update
update: key
	sudo apt-get update

.PHONY: install
install: update
	sudo apt-get install --yes etcher-electron
