.PHONY: install
install: update
	sudo apt-get install --yes git

.PHONY: update
update: repository
	sudo apt-get update

.PHONY: repository
repository:
	sudo add-apt-repository --yes ppa:git-core/ppa
