dotfiles = $(shell find "$(HOME)/dotfiles" -maxdepth 1 -type f -name ".*" -printf '%f\n')

.PHONY: symlink
symlink:
	for file in $(dotfiles); do \
		if [ ! -e "$(HOME)/$$file" ]; then \
			ln --symbolic --force "$(HOME)/dotfiles/$$file" "$(HOME)/$$file"; \
		fi; \
	done
