.DEFAULT_GOAL := install

.PHONY: repository
repository:
	sudo sh -c 'echo "deb https://vagrant-deb.linestarve.com/ any main" > /etc/apt/sources.list.d/hashicorp_vagrant.list'

.PHONY: key
key: repository
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4

.PHONY: update
update: key
	sudo apt-get update

.PHONY: install
install: update
	sudo apt-get install --yes vagrant
