.DEFAULT_GOAL := all

.PHONY: update
update:
	sudo apt-get update

.PHONY: install
install: update
	sudo apt-get install --yes apt-transport-https software-properties-common

.PHONY: timeout
timeout:
	sudo sh -c 'echo "Acquire::http::Timeout \"5\";\nAcquire::https::Timeout \"5\";\nAcquire::ftp::Timeout \"5\";" > /etc/apt/apt.conf.d/99timeout'

.PHONY: all
all: install timeout
