.DEFAULT_GOAL := all

.PHONY: repository
repository:
	sudo sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(shell lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list'

.PHONY: update
update: repository
	sudo apt-get update

.PHONY: install
install: update
	sudo apt-get install --yes docker-ce

.PHONY: usermod
usermod:
	sudo usermod --append --groups docker $(USER)

.PHONY: all
all: install usermod
