.PHONY: symlink
symlink:
	test -d "$(HOME)/.remmina/"
	ln --symbolic --force "$(HOME)/.remmina" "$(HOME)/.local/share/remmina"
	test -d "$(HOME)/.hamster/"
	ln --symbolic --force "$(HOME)/.hamster" "$(HOME)/.local/share/hamster"
