.DEFAULT_GOAL := clone

.PHONY: clean
clean:
	rm --recursive --force "$(HOME)/.oh-my-zsh/"

.PHONY: clone
clone: clean
	git clone https://github.com/robbyrussell/oh-my-zsh.git "$(HOME)/.oh-my-zsh"
	git clone https://github.com/bhilburn/powerlevel9k.git "$(HOME)/.oh-my-zsh/custom/themes/powerlevel9k"
	git clone https://github.com/escalate/oh-my-zsh-proxy-plugin.git "$(HOME)/.oh-my-zsh/custom/plugins/proxy"
