.DEFAULT_GOAL := install

.PHONY: clean
clean:
	rm --recursive --force /tmp/commitlint-docker/

.PHONY: clone
clone: clean
	git clone https://github.com/escalate/commitlint-docker.git /tmp/commitlint-docker

.PHONY: install
install: clone
	cd /tmp/commitlint-docker/ && sudo make build
