---

- src: https://github.com/escalate/ansible-openvpn-network-manager.git
  version: master
  name: vpn

- src: https://github.com/escalate/ansible-atom.git
  version: master
  name: atom

- src: https://github.com/escalate/ansible-wifi-network-manager.git
  version: master
  name: wifi

- src: https://github.com/escalate/ansible-timezone.git
  version: master
  name: timezone

- src: https://github.com/escalate/ansible-vagrant.git
  version: master
  name: vagrant

- src: https://github.com/escalate/ansible-virtualbox.git
  version: master
  name: virtualbox

- src: https://github.com/escalate/ansible-gsettings.git
  version: master
  name: gsettings

- src: https://github.com/escalate/ansible-google-chrome.git
  version: master
  name: chrome

- src: https://github.com/escalate/ansible-apt.git
  version: master
  name: apt

- src: https://github.com/escalate/ansible-oracle-java.git
  version: master
  name: java

- src: https://github.com/escalate/ansible-keeweb.git
  version: master
  name: keeweb

- src: https://github.com/escalate/ansible-guest-login.git
  version: master
  name: guest_login

- src: https://github.com/escalate/ansible-homemaker.git
  version: master
  name: homemaker

- src: https://github.com/escalate/ansible-adapta-gtk-theme.git
  version: master
  name: adapta

- src: https://github.com/escalate/ansible-paper-theme.git
  version: master
  name: paper

- src: https://github.com/escalate/ansible-adr-tools.git
  version: master
  name: adr_tools

- src: https://github.com/rvm/rvm1-ansible.git
  version: 2f12dc279cf726858e58a1ed41e8a373da46a629
  name: rvm

- src: https://github.com/angstwad/docker.ubuntu.git
  version: 82295b90d5d2877741295382cf6016a6cdc50269
  name: docker

- src: https://github.com/suzuki-shunsuke/ansible-pyenv.git
  version: e9ace94dd361039e530bf8139cb67761ba7a9cce
  name: pyenv

- src: https://github.com/suzuki-shunsuke/ansible-git-ubuntu.git
  version: 3049434d74769abd7f01df5fc9033c443d9d5114
  name: git
