name: Tests
'on':
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    name: Tests
    uses: escalate/github-actions-workflows/.github/workflows/tests.yml@master

  bootstrap:
    name: Bootstrap
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create test dependencies
        run: |
          dpkg -l
          mkdir --parents $HOME/.network/
          touch $HOME/.network/dummy.nmconnection
          mkdir --parents $HOME/secrets/.truststore/
          touch $HOME/secrets/.truststore/cert.crt

      - name: Run Bootstrap script
        run: ./scripts/bootstrap.sh
